* Introduction

  =Lua0x= is a very simple c++11 library for registering c++ lambdas
  under a lua module (see the example below). It is intended to be
  lightweight, thus easily copy-pasta'd where needed.

  It works by wrapping lambdas under =std::function= objects, and
  registering the =std::function= types to luabind when needed. Any
  function parameter/return types will work as long as they are
  registered with luabind before function calls (basic types and
  =std::string= are already).
  
* Requirements
  
  The basic code dependencies are =lua= 5.1 and =luabind=. A decent
  c++11 compiler is also needed (=auto=, lambdas and template aliases
  are needed). 

  The build "system" uses QMake and pkg-config. The following command
  should take care of everything under Debian/Ubuntu:

: sudo apt-get install lua5.1 libluabind-dev qt4-qmake pkg-config
  
  Have a look at =lua0x.pro= to build as a library or an example
  executable.

* Example

Taken from =main.cpp=:

#+BEGIN_SRC CPP
#include "module.h"
#include "state.h"

int main(int, char** ) {

  // lua state wrapper
  lua::state state;

  // init stuff and declare a global lua module 'cxx'
  lua::module::init( state, "cxx" );
  
  // declare a lua module under global name 'test'
  lua::module test("test");

  // binds a c++11 lambda as test.echo
  test("echo", [](const std::string& name) { 
      std::cout << name << std::endl; 
    });
  
  // register test module in lua
  state.string("cxx.load('test')");
  
  // calls test.echo
  state.string("test.echo('lolwat')");
  
  return 0;
}
#+END_SRC


* License

  LGPL 2.1

  
